steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest', 'mail_microservice']

  # Docker push to Google Cloud Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest']