name: CI Pipeline

on:
  push:
    branches:
      - test

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r mail_microservice/requirements.txt

    - name: Run unit tests
      run: |
        cd mail_microservice
        python -m unittest discover

  build-and-push:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to Google Container Registry
      uses: docker/login-action@v3.1.0
      with:
        registry: europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: mail_microservice
        push: true
        tags: europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest

  e2e-tests:
    needs: build-and-push
    runs-on: ubuntu-latest
    services:
      flask:
        image: europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://localhost:5000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install TestCafe
      run: npm install -g testcafe

    - name: Run TestCafe tests
      run: testcafe chrome test_frontend.js
