name: Deploy to Cloud Run

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: onzecord-mail
          region: europe-west3
          project_id: onzecord-416813
          image: europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:${SHORT_SHA}
          platform: managed
          allow-unauthenticated: true
          port: 5000